### ISSUE TITLE
NS api link

### ISSUE THREAD

**Issue by alfureu** [xaviermur/nightscout-trayicon-monitor#1]
Just discovered this app. I was wondering how the config works, as I do not have the NS instance on heroku but I self-host

So instead of 
```
https://[YOUR_PASS]@[YOUR_USER].herokuapp.com/api/v1/```
```

I have the link something like this:
```
https://subdomain.domain.com/api/v1/entries?token=xxx-12894328643"
```

I tried to edit the config file with the link, with all sort of combinations, however, it did not work. When I load the link in the browser, I can see the entries in an XML format. Could you suggest how to format the link?

**Comment by xaviermur** [comment]
Hey! It's been a long time since I developed this little app! I guess there was a problem getting the logs from NS when you were using the token instead of USER + PASS. 
I've published a new version (0.0.2). Now the information is retrieved through a token, as you proposed. It's much better this way! Now it should work.
Thanks for your feedback!
Regards.

**Comment by alfureu** [comment]
Thanks I can connect now to the server. Do you think it would be possible to also show entries in mmol/L? I cannot see the option for this in the config file

**Comment by xaviermur** [comment]
Hi! I've seen that you can change units settings in the NS web:
![image](https://user-images.githubusercontent.com/20679040/151165649-ceeadc05-9b79-41b9-9484-69eb40c8dc44.png)
...unfortunately the data returned by the NS api is always in mg/dL.
Thanks for your feedback, I'll include this options in the next version.

**Comment by alfureu** [comment]
I can confirm such an option is available in NS. Would be lovely to have this also in the tray bar. Thanks in advance!

**Comment by xaviermur** [comment]
Hey @DOFfactory,
I've published a new version with the option to show the entries in mmol/L. 
When you open the app for the first time, it allows you to fill in the configuration (no need to edit the app.config anymore).
In this setting, you can mark how you want to view the entries (mg/dL or mmol/L).
If you want to change any configuration parameter, you can do it with a right click on the tray icon of the application.
Regards.

**Comment by alfureu** [comment]
Thanks, I am testing it. What I can observe at the moment that if you have a value like 11.4 or similar, the beginning of the first number is a bit cut off (i think due to the lack of space in the tray)

![image](https://user-images.githubusercontent.com/10846169/151309627-022a28b8-df39-45b6-8975-5c900fa2159c.png)

EDIT: screenshot added
